[[TypeDBClient3_jll]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0631822354eb0835a8449f90ad1df9e0b08b5b9d"
julia_version = "1.10.4"
libgfortran_version = "5.0.0"
os = "macos"
[[TypeDBClient3_jll]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0631822354eb0835a8449f90ad1df9e0b08b5b9d"
julia_version = "1.12.5"
libgfortran_version = "5.0.0"
os = "macos"
[[TypeDBClient3_jll]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbacd8bc790e511841d85677cfd425f0b882e9ee"
julia_version = "1.10.11"
libgfortran_version = "5.0.0"
os = "macos"
[[TypeDBClient3_jll]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "786f6a118299fd74880884eae6a7e2d3f7bc1a1d"
julia_version = "1.12.5"
libgfortran_version = "5.0.0"
os = "macos"
